OBJS-$(CONFIG_H264CHROMA)                += riscv/h264_chroma_init_riscv.o
OBJS-$(CONFIG_H264QPEL)                  += riscv/h264_qpel_init_riscv.o

RVV-OBJS-$(CONFIG_H264CHROMA)            += riscv/h264_mc_chroma.o
RVV-OBJS-$(CONFIG_H264QPEL)              += riscv/h264_mc_luma.o